name: Signing Reusable Workflow

inputs:
  packageFormat:
    description: Package formats to build
    required: true
    default: "apk"
  packageFlavor:
    description: Package flavor
    required: true
    default: "full"
  appName:
    description: app- name to sign for
    required: true
    default: "app-thunderbird"
  releaseType:
    description: Release Type
    required: true
    default: "debug"
  signingKey:
    description: Base64 signing key
    required: true
  alias:
    description: key alias
    required: true
  keyPassword:
    description: key password
    required: true
  keyStorePassword:
    description: key store password
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: unsigned-${{ inputs.packageFormat }}-${{ inputs.packageFlavor }}
        path: uploads/

    - uses: noriban/sign-android-release@5f144321d3c7c2233266e78b42360345d8bbe403   # v5.1
      name: Sign package
      with:
        releaseDirectory: uploads/
        signingKeyBase64: ${{ inputs.signingKey }}
        alias: ${{ inputs.alias }}
        keyPassword: ${{ inputs.keyPassword }}
        keyStorePassword: ${{ inputs.keyStorePassword }}

    - name: Remove JKS file
      shell: bash
      run: |
        rm -f uploads/*.jks

    - name: Upload signed
      uses: actions/upload-artifact@v4
      with:
        name: signed-${{ inputs.packageFormat }}-${{ inputs.packageFlavor }}
        if-no-files-found: error
        path: |
          artifacts/*.apk
          artifacts/*.aab
          !artifacts/*.jks

